### PR TITLE
BAH-2792 | Updated to set obsDateTime to bahmniObservations.

### PR DESCRIPTION
**Pull request by deepthi-mantena**

### CODE REVIEW

**Comment by gsluthra** [comment]
Even though this is a small code addition, I am worried about its impact. Does this cause some regression issues to come, since the code seems to be a fundamental class, and obs date time decides report chronology / obs chrnology, etc. Will need to understand more on why this is done, and how do we know it isn't breaking anything? @gokultw

**Comment by gokultw** [comment]
@deepthi-mantena can we have a desk check to understand more on this?

**Comment by deepthi-mantena** [comment]
Sure Gokul we can connect

**Comment by gsluthra** [comment]
@gokultw @deepthi-mantena - Did u folks connect on this?

**Comment by deepthi-mantena** [comment]
No Gurpreet we will connect today.

**Pull request merged**
